services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "localhost:9092"]
      interval: 10s
      timeout: 5s
      retries: 5

  cassandra:
    image: cassandra:4.1
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "PlantMonitoringCluster"
      CASSANDRA_NUM_TOKENS: 256
      CASSANDRA_START_RPC: "true"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - cassandra-data:/var/lib/cassandra
  
  # Spark Batch Learning Container (For Training Only)
  # spark-batch-learning:
  #   build: ./spark-batch-learning
  #   depends_on:
  #     cassandra:
  #       condition: service_healthy
  #   command: >
  #     spark-submit
  #     --packages com.datastax.spark:spark-cassandra-connector_2.12:3.4.1
  #     app.py

  # emqx:
  #   image: emqx/emqx-enterprise:5.3.0-full
  #   ports:
  #     - "1883:1883"
  #     - "18083:18083"

  mqtt-kafka-bridge:
    build: ./mqtt-kafka-bridge
    depends_on:
      - kafka
    restart: unless-stopped
    env_file:
      - ./mqtt-kafka-bridge/.env
    environment:
      - PYTHONUNBUFFERED=1

  raw-data-consumer:
    build: ./raw-data-consumer
    depends_on:
      kafka:
        condition: service_healthy
      cassandra:
        condition: service_healthy

  weather-api:
    build: ./weather-api
    depends_on:
      kafka:
        condition: service_healthy
    env_file:
      - ./weather-api/.env
    environment:
      - NODE_OPTIONS=--dns-result-order=ipv4first

volumes:
  cassandra-data: